# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pmUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmName', models.CharField(max_length=150)),
                ('transMaxLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmPosition', models.CharField(max_length=150)),
                ('uTel', models.CharField(max_length=50)),
                ('uEmail', models.CharField(max_length=50)),
                ('cDate', models.DateField(default=datetime.datetime(2017, 6, 12, 12, 19, 40, 474894, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='portfolioManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmName', models.CharField(max_length=250)),
                ('pmAutorPerson', models.CharField(max_length=250)),
                ('pmPhone', models.CharField(max_length=50)),
                ('pmAddress', models.CharField(max_length=500)),
                ('pmEmail', models.CharField(max_length=50)),
                ('pmCountry', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='pmusers',
            name='pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliomanager.portfolioManager'),
        ),
        migrations.AddField(
            model_name='pmusers',
            name='sUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
