# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('portfoliomanager', '0002_auto_20170612_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomanager',
            name='sgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pmusers',
            name='cDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 12, 12, 20, 16, 866760, tzinfo=utc)),
        ),
    ]
