# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170606_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpfdates',
            name='pfDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 6, 31, 1, 873750, tzinfo=utc)),
        ),
    ]
