# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20170606_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='inputUser',
            new_name='imUser',
        ),
        migrations.AlterField(
            model_name='stockpfdates',
            name='pfDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 6, 38, 6, 605056, tzinfo=utc)),
        ),
    ]
