# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170606_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpfdates',
            name='pfDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 7, 38, 19, 939822, tzinfo=utc)),
        ),
    ]
