# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20170606_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpfdates',
            name='pfDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 9, 5, 43, 23, 591796, tzinfo=utc)),
        ),
    ]
