# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20170609_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpfdates',
            name='pfDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 9, 5, 45, 29, 109976, tzinfo=utc)),
        ),
    ]
